# Generated by Django 4.1.5 on 2023-01-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
